"""Versioned local project persistence API."""

from .manager import ProjectManager, RecentProject, RecentProjectStore, UnsavedChangesDecision
from .schema import (
    PROJECT_FILE_EXTENSION,
    PROJECT_INPUT_SPECS,
    PROJECT_SCHEMA_VERSION,
    ProjectDocument,
    ProjectInputValue,
    ProjectMetadata,
    ProjectModel,
    ProjectValidationError,
    ResultSnapshot,
    build_project_inputs,
    create_project_document,
    flatten_project_inputs,
    missing_feedback_record_ids,
    project_inputs_hash,
    uncertainty_parameters_from_payload,
    uncertainty_parameters_to_payload,
    utc_now_iso,
    validate_project_document,
)
from .serializer import (
    ProjectIntegrityError,
    ProjectSerializationError,
    UnsupportedProjectVersionError,
    load_project,
    migrate_project,
    project_to_payload,
    save_project,
    serialize_project,
    validate_project,
)

__all__ = [
    "PROJECT_FILE_EXTENSION",
    "PROJECT_INPUT_SPECS",
    "PROJECT_SCHEMA_VERSION",
    "ProjectDocument",
    "ProjectInputValue",
    "ProjectIntegrityError",
    "ProjectManager",
    "ProjectMetadata",
    "ProjectModel",
    "ProjectSerializationError",
    "ProjectValidationError",
    "RecentProject",
    "RecentProjectStore",
    "ResultSnapshot",
    "UnsupportedProjectVersionError",
    "UnsavedChangesDecision",
    "build_project_inputs",
    "create_project_document",
    "flatten_project_inputs",
    "load_project",
    "migrate_project",
    "missing_feedback_record_ids",
    "project_inputs_hash",
    "project_to_payload",
    "save_project",
    "serialize_project",
    "uncertainty_parameters_from_payload",
    "uncertainty_parameters_to_payload",
    "utc_now_iso",
    "validate_project",
    "validate_project_document",
]
