"""Read-only validation utilities that remain outside the production calculator."""

from .accuracy_metrics import AccuracyMetricStatus, AccuracyMetrics, compute_accuracy_metrics
from .external_metric_comparison import (
    ComparabilityStatus,
    ComparisonOutcome,
    EvidenceType,
    ExternalMetricComparison,
    ExternalMetricEvidence,
    ExternalValidationCampaignResult,
    MetricProvenance,
    SafeTransformation,
    compare_external_metric,
)
from .fea_import import (
    ExternalFEAImportAdapter,
    FEAImportedMeshMetadata,
    FEAWaveformMetrics,
    FEAWaveformSample,
    ImportedFEAReference,
    analyze_periodic_waveform,
    sha256_file,
)
from .fea_reference import (
    EvidenceClassification as FEAEvidenceClassification,
    FEADimensionality,
    FEAExecutionStatus,
    FEAFidelityTier,
    FEAMeshConvergencePoint,
    FEAMeshConvergenceResult,
    FEAReferenceDefinition,
    FEASolverMetadata,
    assess_mesh_convergence,
    load_fea_reference_definition,
)
from .phase7a_baseline import (
    AccuracyBaselineRow,
    BaselineOutcome,
    Phase7ABaselineResult,
    TargetLock,
    ValidationStatus,
    run_phase7a_accuracy_baseline,
)
from .phase7b1_campaign import build_phase7b1_campaign, render_phase7b1_report, run_phase7b1_campaign
from .phase7c_reconstruction import (
    BlockerCategory,
    BlockerResolution,
    Phase7CResult,
    build_phase7c_result,
    render_phase7c_report,
    run_phase7c_reconstruction,
)
from .reconstructed_cases import (
    MissingReconstructedInputError,
    ReconstructedAFPMCase,
    ReconstructedCaseError,
    ReconstructedField,
    ReconstructedFieldStatus,
    SafeDerivedValue,
    load_reconstructed_case,
    normalize_copper_resistance_temperature,
    require_reconstructed_inputs,
    synchronous_reactance_to_inductance_h,
)

__all__ = [
    "AccuracyBaselineRow",
    "AccuracyMetricStatus",
    "AccuracyMetrics",
    "BaselineOutcome",
    "BlockerCategory",
    "BlockerResolution",
    "ComparabilityStatus",
    "ComparisonOutcome",
    "EvidenceType",
    "ExternalFEAImportAdapter",
    "ExternalMetricComparison",
    "ExternalMetricEvidence",
    "ExternalValidationCampaignResult",
    "FEADimensionality",
    "FEAEvidenceClassification",
    "FEAExecutionStatus",
    "FEAImportedMeshMetadata",
    "FEAFidelityTier",
    "FEAMeshConvergencePoint",
    "FEAMeshConvergenceResult",
    "FEAReferenceDefinition",
    "FEASolverMetadata",
    "FEAWaveformMetrics",
    "FEAWaveformSample",
    "ImportedFEAReference",
    "MetricProvenance",
    "MissingReconstructedInputError",
    "Phase7ABaselineResult",
    "Phase7CResult",
    "ReconstructedAFPMCase",
    "ReconstructedCaseError",
    "ReconstructedField",
    "ReconstructedFieldStatus",
    "SafeTransformation",
    "SafeDerivedValue",
    "TargetLock",
    "ValidationStatus",
    "analyze_periodic_waveform",
    "assess_mesh_convergence",
    "compute_accuracy_metrics",
    "compare_external_metric",
    "build_phase7b1_campaign",
    "build_phase7c_result",
    "load_reconstructed_case",
    "load_fea_reference_definition",
    "normalize_copper_resistance_temperature",
    "render_phase7b1_report",
    "render_phase7c_report",
    "require_reconstructed_inputs",
    "run_phase7a_accuracy_baseline",
    "run_phase7b1_campaign",
    "run_phase7c_reconstruction",
    "sha256_file",
    "synchronous_reactance_to_inductance_h",
]
