"""Phase 6B isolated PMSM time-domain simulation foundation."""

from .configuration import (
    FallbackPolicy,
    ResolvedSimulationSettings,
    SimulationAccuracy,
    SimulationConfig,
    SolverPreference,
    select_simulation_settings,
)
from .controllers import (
    DQCurrentController,
    DQDecouplingFeedforward,
    DQSaturationFeedback,
    DQVoltageCommand,
    FieldWeakeningController,
    FieldWeakeningResult,
    FieldWeakeningVoltageEstimate,
    MTPAController,
    MTPACurrentReference,
    PIController,
    SpeedController,
    SpeedControllerConfig,
    SpeedControllerOutput,
    SpeedControllerState,
    compute_pmsm_dq_decoupling_feedforward,
)
from .current_control_runner import (
    CurrentControlSimulationRunner,
    CurrentReferenceProfile,
    DQCurrentReference,
)
from .foc_runner import (
    FOCReference,
    FOCRunner,
    FOCRunnerConfig,
    FOCSimulationResult,
    FOCStepInput,
    FOCStepOutput,
    ScalarProfile,
    run_foc_current_control_simulation,
)
from .integrators import DerivativeEvaluator, EulerIntegrator, RK4Integrator
from .inverter import DCBusConfig, InverterVoltageLimiter, VoltageLimitResult
from .losses import (
    CopperLossModel,
    DynamicLossModel,
    IronLossEstimate,
    IronLossModel,
    LossBreakdown,
    LossModelConfig,
    MechanicalLossModel,
    ProvisionalIronLossModel,
    ResistanceTemperatureConfig,
    UnavailableIronLossModel,
)
from .modulation import (
    SVPWMConfig,
    SVPWMModulator,
    SVPWMResult,
    VoltageApplicationMode,
)
from .pmsm_model import PMSMDynamicModel, PMSMDynamicParameters
from .modulation_experiments import (
    ModulationExampleResult,
    SpeedModeComparison,
    SpeedModeMetrics,
    run_direct_modulation_examples,
    run_speed_mode_comparison,
)
from .sensors import (
    CurrentSensor,
    CurrentSensorConfig,
    PositionMeasurement,
    PositionSensor,
    PositionSensorConfig,
    SensorMeasurement,
    SensorSuite,
    SensorSuiteConfig,
    SensorSuiteMeasurement,
    SpeedSensor,
    SpeedSensorConfig,
)
from .sensor_experiments import (
    CurrentSensorErrorExperimentResult,
    RotorAngleErrorExperimentResult,
    run_current_sensor_error_experiments,
    run_rotor_angle_error_experiments,
)
from .simulation_results import SimulationConfidence, SimulationResult, SimulationStatus
from .simulation_runner import InputProfile, SimulationRunner
from .state import DQElectricalDerivatives, InputState, MotorState, StateDerivatives
from .speed_control_runner import (
    SpeedControlRunnerConfig,
    SpeedControlSimulationResult,
    SpeedControlSimulationRunner,
    run_speed_load_step_example,
    run_speed_startup_example,
    run_unreachable_speed_example,
)
from .transforms import (
    ABCPhaseValues,
    AlphaBetaValues,
    DQValues,
    clarke_transform,
    electrical_angle,
    inverse_clarke_transform,
    inverse_park_transform,
    park_transform,
    wrap_electrical_angle,
)
from .thermal import (
    LumpedThermalModel,
    ThermalConfig,
    ThermalDerivative,
    ThermalElectricalCouplingConfig,
    ThermalIntegrationMethod,
    ThermalState,
)
from .thermal_simulation_runner import (
    ThermalElectricalSimulationRunner,
    ThermalSimulationResult,
)
from .thermal_experiments import (
    PrescribedCurrentThermalResult,
    ThermalExperimentSuite,
    run_thermal_foundation_experiments,
)
from .user_interface import StaticFallbackProvider, UserSimulationRunner, run_user_simulation

__all__ = [
    "ABCPhaseValues",
    "AlphaBetaValues",
    "EulerIntegrator",
    "DerivativeEvaluator",
    "DQElectricalDerivatives",
    "DQCurrentController",
    "DQDecouplingFeedforward",
    "DQCurrentReference",
    "DQVoltageCommand",
    "DQSaturationFeedback",
    "DQValues",
    "DCBusConfig",
    "FallbackPolicy",
    "FOCReference",
    "FOCRunner",
    "FOCRunnerConfig",
    "FOCSimulationResult",
    "FOCStepInput",
    "FOCStepOutput",
    "FieldWeakeningController",
    "FieldWeakeningResult",
    "FieldWeakeningVoltageEstimate",
    "InputProfile",
    "InputState",
    "InverterVoltageLimiter",
    "MotorState",
    "MTPAController",
    "MTPACurrentReference",
    "ModulationExampleResult",
    "PMSMDynamicModel",
    "PMSMDynamicParameters",
    "PIController",
    "RK4Integrator",
    "ResolvedSimulationSettings",
    "SimulationAccuracy",
    "SimulationConfidence",
    "SimulationConfig",
    "SimulationResult",
    "SimulationRunner",
    "SimulationStatus",
    "ScalarProfile",
    "SolverPreference",
    "SpeedController",
    "SpeedControllerConfig",
    "SpeedControllerOutput",
    "SpeedControllerState",
    "SpeedModeComparison",
    "SpeedModeMetrics",
    "SpeedControlRunnerConfig",
    "SpeedControlSimulationResult",
    "SpeedControlSimulationRunner",
    "StaticFallbackProvider",
    "StateDerivatives",
    "UserSimulationRunner",
    "VoltageLimitResult",
    "VoltageApplicationMode",
    "SVPWMConfig",
    "SVPWMModulator",
    "SVPWMResult",
    "CurrentControlSimulationRunner",
    "CurrentReferenceProfile",
    "CurrentSensor",
    "CurrentSensorConfig",
    "CurrentSensorErrorExperimentResult",
    "PositionMeasurement",
    "PositionSensor",
    "PositionSensorConfig",
    "RotorAngleErrorExperimentResult",
    "SensorMeasurement",
    "SensorSuite",
    "SensorSuiteConfig",
    "SensorSuiteMeasurement",
    "SpeedSensor",
    "SpeedSensorConfig",
    "clarke_transform",
    "compute_pmsm_dq_decoupling_feedforward",
    "electrical_angle",
    "inverse_clarke_transform",
    "inverse_park_transform",
    "park_transform",
    "run_user_simulation",
    "run_foc_current_control_simulation",
    "run_direct_modulation_examples",
    "run_current_sensor_error_experiments",
    "run_rotor_angle_error_experiments",
    "run_speed_load_step_example",
    "run_speed_mode_comparison",
    "run_speed_startup_example",
    "run_unreachable_speed_example",
    "select_simulation_settings",
    "wrap_electrical_angle",
    "CopperLossModel",
    "DynamicLossModel",
    "IronLossEstimate",
    "IronLossModel",
    "LossBreakdown",
    "LossModelConfig",
    "LumpedThermalModel",
    "MechanicalLossModel",
    "ProvisionalIronLossModel",
    "ResistanceTemperatureConfig",
    "ThermalConfig",
    "ThermalDerivative",
    "ThermalElectricalCouplingConfig",
    "ThermalElectricalSimulationRunner",
    "ThermalIntegrationMethod",
    "ThermalSimulationResult",
    "ThermalState",
    "UnavailableIronLossModel",
    "PrescribedCurrentThermalResult",
    "ThermalExperimentSuite",
    "run_thermal_foundation_experiments",
]
